### ISSUE TITLE
Disable badges when disabling notebook creation

### ISSUE THREAD

**Issue by BeastyBlacksmith** [johnnychen94/DemoCards.jl#102]
When I disable notebook generation it still generates the badges for downloading the (not existent) notebooks

**Comment by johnnychen94** [comment]
Unsure of how to reproduce it, both the [JuliaImages demos](https://juliaimages.org/stable/examples/) and [Algebra of Graphics gallery](http://juliaplots.org/AlgebraOfGraphics.jl/dev/gallery/) disable the notebook generation and there are no badges for notebooks...

**Comment by BeastyBlacksmith** [comment]
I might be doing something wrong in https://github.com/JuliaPlots/PlotDocs.jl/pull/256 then

**Comment by johnnychen94** [comment]
> I might be doing something wrong in https://github.com/JuliaPlots/PlotDocs.jl/pull/256 then

```json
{
    "theme": "grid",
    "properties": {
        "notebook": "false"
    }
}
```

https://github.com/JuliaPlots/PlotDocs.jl/pull/275 should work.
