### ISSUE TITLE
QR hangup during Windows build

### ISSUE THREAD

**Issue by AP6YC** [johnnychen94/DemoCards.jl#112]
First off, I really appreciate the work that you have put into this project; I found it by recommendation through `Augmentor.jl` and `Images.jl` while developing my package documentation.

When developing on Windows, I have an odd bug that I cannot seem to get around that may or may not be caused by `DemoCards.jl`. When building my documentation locally for development, I get the following error:
![image](https://user-images.githubusercontent.com/17498866/164775394-9e189691-7191-4192-b954-d60bcbf8c805.png)

Further digging revealed that a process called `qksqt.exe`, which I assume to be associated with QR, is holding onto the folder, making me have to kill the process before I can manually delete the docs/src/examples/ folder that is autogenerated by `DemoCards.jl` before successfully rerunning. None of this occurs in my GitHub actions CI, however, just locally on both of my Windows machines.

Have I run into some common issue that I am ignorant of the workaround for, or do you otherwise know what might be the problem?

**Comment by johnnychen94** [comment]
Have you tried to use some folder other than Julia's default `dev` folder? For instance, `D:\Julia\AdaptiveResonance`?

**Comment by AP6YC** [comment]
Good recommendation! I tried it on another folder and drive with no issue. It also seemed to end up being a transient issue; I removed the original problem folder that the system would hang on, re-added each file one at a time, and now can't reproduce my issue on the original location.

Thanks for your time. I'll close this issue for now.
